### ISSUE TITLE
wrong ID

### ISSUE THREAD

**Issue by tothpaul** [ansforge/IHE_XDM-exemples#1]
https://github.com/ansforge/IHE_XDM-exemples/blob/main/CR-BIO_2021.01_Microbiologie_V1/Contenu%20du%20ZIP/IHE_XDM/SUBSET01/DOC0001.XML

la référence `<reference value="#CBU-erythrocytes" />` ne correspond pas à la balise `<content ID="CBU-erythtocytes">Erythtocytes</content>` qui est mal orthographiée

**Comment by nmahraz** [comment]
Bonjour,
Désolé pour le retard, le problème a été traité
